export const CATEGORIES_ADDED = 'CATEGORIES_ADDED';
export const IMAGES_ADDED = 'IMAGES_ADDED';
export const MORE_IMAGES_ADDED = 'MORE_IMAGES_ADDED';
export const CURRENT_CATEGORY_ADDED = 'CURRENT_CATEGORY_ADDED';
